import * as React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { dehydrate, QueryClient } from 'react-query';

import { MainLayout } from '@/components/layout';
import { Loader } from '@/components/elements';
import { useAuth } from '@/lib/authentication';
import { get10Songs, use10Songs } from '@/features/songs';
import { NextPageWithLayout } from '@/types';

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery('10songs', get10Songs);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

const Home: NextPageWithLayout = () => {
  const router = useRouter();
  const { user, isUserLoading } = useAuth();
  const { data } = use10Songs();

  if (isUserLoading) {
    return <Loader isFullHeight />;
  }

  if (user) {
    router.replace('/songs');
  }

  return (
    <div>
      <Head>
        <title>The Genre isn&apos;t World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Homepage</div>
    </div>
  );
};

Home.getLayout = (page: React.ReactElement) => <MainLayout>{page}</MainLayout>;

export default Home;
